### ISSUE TITLE
Nov 31 Livestream TODO List

### ISSUE THREAD

**Issue by codereport** [codereport/bqn-format#1]
TODO:
* [x] Trim trailing whitespace (20 min)
* [x] Add missing EOF blank line (5 min)
* [x] Align assignment operators (40 min)
   * [x] General Cases
   * [x] Fix Function Definition bug
   * [x] Fix multiple assigns on single line
   * [x] Exclude pre define expressions that are variables / arrays
* [x] Align comments (20 min)
   * [x] Fix standalone comments
* [x] Be able to run this on a single file
* [x] Hook up to VS Code?

Follow up issues:
* https://github.com/codereport/bqn-format/issues/2
* https://github.com/codereport/bqn-format/issues/3
